<?php

namespace AppBundle\Repository;

/**
 * ProductSoortRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductSoortRepository extends \Doctrine\ORM\EntityRepository
{
}
