# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
              users:
                gebruiker:
                  password: gebruiker1
                  roles: 'ROLE_GEBRUIKER'
                magazijnbeheerder:
                  password: magazijnbeheerder1
                  roles: 'ROLE_MAGAZIJN'
                inkoper:
                  password: inkoper1
                  roles: 'ROLE_INKOOP'
                verkoper:
                  password: inkoper1
                  roles: 'ROLE_VERKOOP'

    access_control:
      - { path: ^/artikel/nieuw, roles: ROLE_INKOOP }
      - { path: ^/artikel/wijzig/*, roles: ROLE_INKOOP }
      - { path: ^/bestelorder/nieuw, roles: ROLE_INKOOP }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic:

            # https://symfony.com/doc/current/security/form_login_setup.html

            #form_login:
            #    login_path: /login
            #    check_path: /login_check
